kind: Service
apiVersion: v1
metadata:
  name: wordpress-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
  #type: LoadBalancer
  selector:
    app: wordpress-ku
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: default
  labels:
    app: wordpress-ku
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress-ku
      track: stable
  template:
    metadata:
      labels:
        app: wordpress-ku
        track: stable
    spec:
      containers:
      - name: wordpress-ku
        image: indradock/blog-app:versi
        ports:
        - containerPort: 80
        env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: mysecretwp
                  key: host
            - name: DB_NAMA
              valueFrom:
                secretKeyRef:
                  name: mysecretwp
                  key: name
            - name: DB_PENGGUNA
              valueFrom:
                secretKeyRef:
                  name: mysecretwp
                  key: user
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysecretwp
                  key: password
                  
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wp-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
  - host: blog.indraku.online
    http:
      paths:
      #- path: /
      - backend:
          serviceName: wordpress-service
          servicePort: 80
